INSERT INTO SOCIAL_MEDIA_API.ACCOUNTS VALUES(default, 'ilhan', '1234', 'ilhan.5453@gmail.com', '05555555555', default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.ACCOUNTS VALUES(default, 'cem', '12345', 'cem_85638@gmail.com', '05555555556', default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.ACCOUNTS VALUES(default, 'deniz', '54321', 'deniz_1298@gmail.com', '05555555557', default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.ACCOUNTS VALUES(default, 'ahmet', '1357', 'ahmet123@gmail.com', '05555555558', default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.POSTS VALUES(default, 1, 'Merhaba Dünya!', default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.POSTS VALUES(default, 3, 'Merhaba Ilhan!', default,  NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.POSTS VALUES(default, 4, 'Bugun hava cok bozdu!', default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.POSTS VALUES(default, 2, 'Hoca imza almaya basladi mi?', default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.INTERACTIONS VALUES(default, 2, 2,'Sana Da Merhaba Deniz!', 0, default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.INTERACTIONS VALUES(default, 2, 1, ' ', 1, default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.INTERACTIONS VALUES(default, 3, 3, 'Gercekten buz gibiydi!', 0, default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.INTERACTIONS VALUES(default, 4, 4, ' ', 1, default, NOW(), NULL);
INSERT INTO SOCIAL_MEDIA_API.INTERACTIONS VALUES(default, 1, 1, ' ', 2, default, NOW(), NULL);
